/**
 * 食疗模块 — 对症食疗（39 种常见不适/疾病）
 * 结构：疾病 → 推荐食材 → 3~5 道菜品
 */
const SHILIAO_DISEASE_DATA = {
  失眠: {
    name: '失眠',
    icon: '😴',
    category: '睡眠情志',
    alias: ['睡不着', '入睡困难', '多梦易醒', '失眠多梦'],
    color: '#6366f1',
    summary: '入睡困难、多梦易醒，多与心脾两虚、阴虚火旺或情志失调有关。',
    principle: '养心安神、补血益气，兼顾健脾和胃，少食辛辣刺激。',
    ingredients: [
      { name: '莲子', role: '养心安神、健脾止泻' },
      { name: '百合', role: '清心安神、润肺' },
      { name: '红枣', role: '补中益气、养血安神' },
      { name: '桂圆', role: '补益心脾、养血安神' },
      { name: '小米', role: '健脾和胃、安神' },
    ],
    dishes: [
      { name: '莲子百合粥', ingredients: '莲子、百合、小米', note: '养心安神，睡前 1～2 小时温服' },
      { name: '桂圆莲子羹', ingredients: '桂圆、莲子、红枣', note: '心脾双补，晚间少量' },
      { name: '甘麦大枣汤', ingredients: '甘草、小麦、红枣', note: '经典安神方，情志失眠可参考' },
      { name: '红枣山药粥', ingredients: '红枣、山药、大米', note: '健脾养血，适合脾虚失眠' },
    ],
    caution: '实热、痰火内扰者不宜过补；睡前少饮茶咖啡；持续失眠请就医。',
    voiceTitle: '失眠食疗：莲子百合养心安神',
    voiceSummary: '失眠多调心脾。推荐莲子、百合、红枣、桂圆、小米，可做莲子百合粥、桂圆莲子羹、甘麦大枣汤、红枣山药粥，睡前温服，少食辛辣。',
    voiceover: '睡不着别硬扛，食疗先调心脾。莲子百合粥养心安神；桂圆莲子羹补心脾；情志不好可参考甘麦大枣汤；脾虚加红枣山药粥。睡前别喝茶咖啡，长期失眠要看医生。',
  },

  便秘: {
    name: '便秘',
    icon: '🚽',
    category: '脾胃消化',
    alias: ['大便干结', '排便困难', '老年性便秘', '肠燥便秘'],
    color: '#a16207',
    summary: '大便干结、排便费力，多见肠燥津亏、脾虚气弱或热结便秘。',
    principle: '润肠通便、益气健脾，多饮水，增膳食纤维，忌辛辣燥热。',
    ingredients: [
      { name: '蜂蜜', role: '润燥通便' },
      { name: '香蕉', role: '润肠生津（熟用）' },
      { name: '黑芝麻', role: '润肠燥、益精血' },
      { name: '菠菜', role: '养血润燥、通肠' },
      { name: '红薯', role: '宽肠通便' },
    ],
    dishes: [
      { name: '蜂蜜芝麻茶', ingredients: '蜂蜜、黑芝麻', note: '晨起空腹温水冲服，润肠' },
      { name: '香蕉牛奶', ingredients: '熟香蕉、牛奶', note: '生津润肠，早餐适量' },
      { name: '菠菜芝麻拌', ingredients: '菠菜、黑芝麻', note: '焯水后凉拌，养血润燥' },
      { name: '蒸红薯', ingredients: '红薯', note: '宽肠通便，温热食用' },
      { name: '核桃仁粥', ingredients: '核桃、大米', note: '润肠通便，老人便秘适用' },
    ],
    caution: '脾胃虚寒腹泻者慎用香蕉、蜂蜜；勿长期依赖泻药；便血腹痛请就医。',
    voiceTitle: '便秘食疗：蜂蜜芝麻润肠方',
    voiceSummary: '便秘宜润肠不猛泻。推荐蜂蜜、香蕉、黑芝麻、菠菜、红薯，可做蜂蜜芝麻茶、香蕉牛奶、菠菜芝麻拌、蒸红薯、核桃仁粥，多饮水增纤维。',
    voiceover: '便秘要润肠，别只靠泻药。晨起蜂蜜芝麻茶；熟香蕉配牛奶；菠菜焯水拌芝麻；蒸红薯宽肠通便；老人可试核桃仁粥。多喝水多吃菜，腹痛便血要看医生。',
  },

  腹泻: {
    name: '腹泻',
    icon: '💧',
    category: '脾胃消化',
    alias: ['拉肚子', '便溏', '脾虚泄泻', '急性腹泻'],
    color: '#0ea5e9',
    summary: '大便稀溏或次数增多，多见脾胃虚寒、湿邪困脾或食积伤胃。',
    principle: '温中健脾、祛湿止泻，急性期清淡温软，忌生冷油腻。',
    ingredients: [
      { name: '山药', role: '健脾止泻' },
      { name: '生姜', role: '温中止呕、散寒' },
      { name: '糯米', role: '健脾暖胃、止泄' },
      { name: '苹果', role: '熟苹果收敛止泻' },
      { name: '莲子', role: '健脾止泻、安神' },
    ],
    dishes: [
      { name: '蒸苹果泥', ingredients: '苹果', note: '熟苹果收敛，小儿腹泻适用' },
      { name: '山药小米粥', ingredients: '山药、小米', note: '健脾止泻，早餐温服' },
      { name: '糯米莲子粥', ingredients: '糯米、莲子', note: '温中健脾，慢性泄泻' },
      { name: '生姜大枣茶', ingredients: '生姜、红枣', note: '温中散寒，受寒腹泻' },
      { name: '芡实山药粥', ingredients: '芡实、山药', note: '健脾固肾，久泻调理' },
    ],
    caution: '急性感染性腹泻、发热脱水请就医；忌生冷瓜果；薏米利尿，泄泻慎用。',
    voiceTitle: '腹泻食疗：山药小米健脾止泻',
    voiceSummary: '腹泻先温脾。推荐山药、生姜、糯米、熟苹果、莲子，可做蒸苹果泥、山药小米粥、糯米莲子粥、生姜大枣茶、芡实山药粥，忌生冷油腻。',
    voiceover: '拉肚子先别乱吃凉菜。熟苹果蒸泥能收敛；山药小米粥健脾止泻；慢性泄泻熬糯米莲子粥；受寒腹泻泡生姜大枣茶；久泻加芡实山药粥。发热脱水要就医，急性期清淡温软。',
  },

  风寒感冒: {
    name: '风寒感冒',
    icon: '🤧',
    category: '呼吸外感',
    alias: ['感冒初起', '恶寒发热', '风寒外感', '受凉感冒'],
    color: '#38bdf8',
    summary: '恶寒重、发热轻、无汗头痛、鼻塞流清涕，属风寒束表。',
    principle: '发汗解表、温中散寒，宜温热清淡，忌生冷油腻。',
    ingredients: [
      { name: '生姜', role: '发汗解表、温中' },
      { name: '大葱', role: '发汗通阳' },
      { name: '红枣', role: '补中益气、调和营卫' },
      { name: '白萝卜', role: '化痰下气' },
      { name: '紫苏', role: '发汗散寒（如有）' },
    ],
    dishes: [
      { name: '葱白生姜汤', ingredients: '葱白、生姜、红糖', note: '初期无汗恶寒，趁热温服发汗' },
      { name: '生姜红糖水', ingredients: '生姜、红糖', note: '散寒暖胃，畏寒腹痛适用' },
      { name: '萝卜生姜汤', ingredients: '白萝卜、生姜', note: '散寒化痰，咳嗽痰白' },
      { name: '生姜大枣茶', ingredients: '生姜、红枣', note: '调和营卫，体虚感冒' },
      { name: '紫苏生姜饮', ingredients: '紫苏叶、生姜', note: '发汗解表，受凉初期' },
    ],
    caution: '高热、黄痰、咽痛属风热忌发汗过甚；老人儿童遵医嘱；症状加重请就医。',
    voiceTitle: '风寒感冒：葱白生姜汤发汗',
    voiceSummary: '风寒感冒宜发汗散寒。推荐生姜、葱白、红枣，可做葱白生姜汤、生姜红糖水、萝卜生姜汤，趁热温服，无汗恶寒初期最有效。',
    voiceover: '受凉感冒初起，趁热发汗。葱白生姜汤加红糖，无汗恶寒最有效；简单版生姜红糖水；咳嗽痰白煮萝卜生姜汤；体虚加红枣生姜茶。高热黄痰是风热，别猛发汗，加重要看医生。',
  },

  咳嗽痰多: {
    name: '咳嗽痰多',
    icon: '😷',
    category: '呼吸外感',
    alias: ['咳嗽', '痰多', '咳痰', '久咳'],
    color: '#22c55e',
    summary: '咳嗽痰多，分寒痰、热痰、燥痰，食疗需辨证选择。',
    principle: '寒痰温化、热痰清热、燥痰润肺，少肥甘，忌烟酒。',
    ingredients: [
      { name: '白萝卜', role: '化痰下气' },
      { name: '梨', role: '生津润燥、化痰' },
      { name: '陈皮', role: '理气化痰' },
      { name: '生姜', role: '温化寒痰' },
      { name: '银耳', role: '滋阴润肺' },
    ],
    dishes: [
      { name: '冰糖雪梨汤', ingredients: '雪梨、冰糖', note: '燥咳少痰、咽干适用' },
      { name: '白萝卜蜂蜜饮', ingredients: '白萝卜、蜂蜜', note: '润肺化痰，痰少而黏' },
      { name: '萝卜生姜汤', ingredients: '白萝卜、生姜', note: '寒痰咳嗽、痰白清稀' },
      { name: '陈皮橙子茶', ingredients: '陈皮、橙子', note: '理气化痰，胸闷痰多' },
      { name: '银耳雪梨羹', ingredients: '银耳、雪梨', note: '阴虚燥咳、干咳少痰' },
    ],
    caution: '黄脓痰、高热胸痛请就医；川贝等药材需遵医嘱；哮喘发作禁盲目食疗。',
    voiceTitle: '咳嗽痰多：先分寒痰热痰燥痰',
    voiceSummary: '咳嗽要辨证。寒痰用萝卜生姜汤；燥咳用冰糖雪梨、白萝卜蜂蜜饮；痰多胸闷用陈皮橙子茶；阴虚干咳用银耳雪梨羹。',
    voiceover: '咳嗽别乱吃梨。痰白清稀是寒痰，萝卜生姜汤；干咳少痰炖冰糖雪梨；痰黏少加白萝卜蜂蜜饮；胸闷痰多泡陈皮橙子茶；阴虚久咳煮银耳雪梨羹。黄脓痰高热要看医生。',
  },

  上火咽痛: {
    name: '上火咽痛',
    icon: '🔥',
    category: '呼吸外感',
    alias: ['咽痛', '喉咙痛', '上火', '口干咽痛'],
    color: '#ef4444',
    summary: '咽喉肿痛、口干口苦，多见肺胃热盛或阴虚火旺。',
    principle: '清热生津、利咽解毒，清淡饮食，忌辛辣烧烤酒类。',
    ingredients: [
      { name: '梨', role: '清热润燥' },
      { name: '绿豆', role: '清热解毒' },
      { name: '菊花', role: '疏散风热、清肝' },
      { name: '黄瓜', role: '清热利水' },
      { name: '苦瓜', role: '清热降火' },
    ],
    dishes: [
      { name: '冰糖雪梨汤', ingredients: '雪梨、冰糖', note: '润肺利咽，咽干咽痛' },
      { name: '绿豆汤', ingredients: '绿豆', note: '清热解毒，暑热火盛' },
      { name: '菊花金银花茶', ingredients: '菊花、金银花', note: '清热利咽，少量温饮' },
      { name: '盐蒸橙子', ingredients: '橙子、盐', note: '化痰润喉，风热咳嗽咽痛' },
      { name: '黄瓜蜂蜜水', ingredients: '黄瓜、蜂蜜', note: '生津润燥，口干上火' },
    ],
    caution: '化脓性扁桃体炎、高热请就医；脾胃虚寒者少饮寒凉；服药期间遵医嘱。',
    voiceTitle: '上火咽痛：梨汤菊花茶清热',
    voiceSummary: '上火咽痛宜清热生津。冰糖雪梨汤、绿豆汤、菊花金银花茶、盐蒸橙子、黄瓜蜂蜜水，清淡饮食忌辛辣烧烤。',
    voiceover: '喉咙痛上火，先清热生津。炖冰糖雪梨汤；暑热重煮绿豆汤；泡菊花金银花茶；盐蒸橙子润喉；口干喝黄瓜蜂蜜水。化脓发烧要就医，胃寒别猛喝凉的。',
  },

  湿气重: {
    name: '湿气重',
    icon: '💦',
    category: '代谢湿浊',
    alias: ['祛湿', '身体困重', '头重如裹', '脾虚湿盛'],
    color: '#0891b2',
    summary: '身体困重、头重如裹、大便黏腻，多见脾虚湿困。',
    principle: '健脾祛湿、利水渗湿，少甜腻生冷，适量运动。',
    ingredients: [
      { name: '薏米', role: '健脾渗湿' },
      { name: '红豆', role: '利水消肿' },
      { name: '冬瓜', role: '利水清热' },
      { name: '茯苓', role: '健脾利湿' },
      { name: '陈皮', role: '理气化湿' },
    ],
    dishes: [
      { name: '薏米红豆汤', ingredients: '薏米、红豆', note: '经典祛湿方，少糖' },
      { name: '冬瓜薏米汤', ingredients: '冬瓜、薏米', note: '清热利湿，夏季适用' },
      { name: '红豆陈皮汤', ingredients: '红豆、陈皮', note: '健脾化湿，腹胀纳差' },
      { name: '芡实薏米羹', ingredients: '芡实、薏米', note: '健脾祛湿止泻' },
      { name: '玉米须茶', ingredients: '玉米须', note: '利水消肿，代茶饮用' },
    ],
    caution: '孕妇慎用大剂量薏米；津液不足便秘者不宜久用；祛湿需坚持作息饮食。',
    voiceTitle: '湿气重：薏米红豆经典祛湿',
    voiceSummary: '祛湿靠健脾利水。薏米红豆汤最经典，还可冬瓜薏米汤、红豆陈皮汤、芡实薏米羹、玉米须茶，少甜腻生冷。',
    voiceover: '身体困重大便黏，湿气缠人。薏米红豆汤是经典；夏天加冬瓜同煮；腹胀纳差放陈皮；脾虚泄泻试芡实薏米羹；水肿泡玉米须茶。祛湿要坚持，孕妇薏米要适量。',
  },

  气血不足: {
    name: '气血不足',
    icon: '💗',
    category: '气血虚寒',
    alias: ['气虚血虚', '面色萎黄', '乏力', '气血两虚'],
    color: '#ec4899',
    summary: '面色萎黄、神疲乏力、心悸气短，多见气血亏虚。',
    principle: '益气补血、健脾养胃，规律作息，忌过劳生冷。',
    ingredients: [
      { name: '红枣', role: '补中益气、养血' },
      { name: '桂圆', role: '补血安神' },
      { name: '当归', role: '补血活血' },
      { name: '鸡肉', role: '温中益气' },
      { name: '花生', role: '养血止血' },
    ],
    dishes: [
      { name: '红枣桂圆茶', ingredients: '红枣、桂圆', note: '养血安神，日常温饮' },
      { name: '当归红枣鸡汤', ingredients: '当归、红枣、鸡肉', note: '气血双补，女性调养' },
      { name: '花生红枣粥', ingredients: '花生、红枣、大米', note: '健脾养血，早餐温服' },
      { name: '黄芪炖鸡', ingredients: '黄芪、鸡肉', note: '益气固表，乏力气短' },
      { name: '桂圆小米粥', ingredients: '桂圆、小米', note: '补血安神，产后体虚' },
    ],
    caution: '实热、湿盛中满者不宜过补；糖尿病控枣桂圆用量；需排除器质性疾病。',
    voiceTitle: '气血不足：红枣桂圆当归补养',
    voiceSummary: '气血不足宜益气补血。红枣桂圆茶、当归红枣鸡汤、花生红枣粥、黄芪炖鸡、桂圆小米粥，规律作息忌过劳。',
    voiceover: '脸色黄、总没劲，多是气血不足。日常泡红枣桂圆茶；炖当归红枣鸡汤；早餐花生红枣粥；容易累用黄芪炖鸡；产后体虚熬桂圆小米粥。实热痰湿别猛补，血糖高控枣量。',
  },

  脾胃虚寒: {
    name: '脾胃虚寒',
    icon: '🥶',
    category: '气血虚寒',
    alias: ['胃寒', '怕冷', '脾胃虚寒', '腹部冷痛'],
    color: '#78716c',
    summary: '畏寒肢冷、胃脘冷痛、喜温喜按、大便稀溏。',
    principle: '温中散寒、健脾暖胃，忌生冷寒凉，宜温热软烂。',
    ingredients: [
      { name: '生姜', role: '温中散寒' },
      { name: '羊肉', role: '温中补虚' },
      { name: '糯米', role: '健脾暖胃' },
      { name: '红枣', role: '补中温养' },
      { name: '桂圆', role: '温补心脾' },
    ],
    dishes: [
      { name: '生姜红糖水', ingredients: '生姜、红糖', note: '温中散寒，胃寒腹痛' },
      { name: '当归生姜羊肉汤', ingredients: '当归、生姜、羊肉', note: '温中补血，冬季进补' },
      { name: '糯米红枣粥', ingredients: '糯米、红枣', note: '暖胃健脾，早餐温服' },
      { name: '羊肉萝卜汤', ingredients: '羊肉、白萝卜', note: '温中化痰，荤素搭配' },
      { name: '桂圆姜枣茶', ingredients: '桂圆、生姜、红枣', note: '温补气血，畏寒乏力' },
    ],
    caution: '外感发热、阴虚火旺、疮疡者忌温补；高血脂羊肉撇油；痛剧请就医。',
    voiceTitle: '脾胃虚寒：生姜羊肉温中',
    voiceSummary: '脾胃虚寒宜温中暖胃。生姜红糖水、当归生姜羊肉汤、糯米红枣粥、羊肉萝卜汤、桂圆姜枣茶，忌生冷寒凉。',
    voiceover: '胃怕冷、喜热按，是脾胃虚寒。喝生姜红糖水；冬天炖当归生姜羊肉汤；早餐糯米红枣粥；羊肉萝卜汤温中化痰；畏寒泡桂圆姜枣茶。发烧上火别温补，剧痛要看医生。',
  },

  肾虚腰酸: {
    name: '肾虚腰酸',
    icon: '🦴',
    category: '肾腰免疫',
    alias: ['腰酸', '腰膝酸软', '肾虚', '腰膝酸冷'],
    color: '#854d0e',
    summary: '腰膝酸软、畏寒乏力，多见肾阳虚或肾精不足。',
    principle: '补肾益精、温阳强腰，忌过劳熬夜，宜温补缓进。',
    ingredients: [
      { name: '核桃', role: '补肾温肺' },
      { name: '黑豆', role: '补肾益阴' },
      { name: '枸杞', role: '滋补肝肾' },
      { name: '山药', role: '补脾益肾' },
      { name: '羊肉', role: '温补肾阳' },
    ],
    dishes: [
      { name: '核桃黑豆粥', ingredients: '核桃、黑豆、大米', note: '补肾健脑，早餐温服' },
      { name: '枸杞山药粥', ingredients: '枸杞、山药', note: '平补脾肾，日常调养' },
      { name: '山药排骨汤', ingredients: '山药、排骨', note: '补肾健脾，病后调养' },
      { name: '当归生姜羊肉汤', ingredients: '当归、生姜、羊肉', note: '温补肾阳，腰膝酸冷' },
      { name: '黑芝麻核桃糊', ingredients: '黑芝麻、核桃', note: '补肝肾益精血' },
    ],
    caution: '阴虚火旺忌过温；急性腰痛外伤查病因；伴水肿尿少请就医。',
    voiceTitle: '肾虚腰酸：核桃黑豆枸杞补肾',
    voiceSummary: '腰酸宜补肾益精。核桃黑豆粥、枸杞山药粥、山药排骨汤、当归生姜羊肉汤、黑芝麻核桃糊，忌过劳熬夜。',
    voiceover: '腰酸怕冷乏力，补肾要缓进。早餐核桃黑豆粥；日常枸杞山药粥；病后调养炖山药排骨汤；腰膝酸冷煲当归生姜羊肉汤；打黑芝麻核桃糊。阴虚火旺别过温，剧痛外伤要查因。',
  },

  血压偏高: {
    name: '血压偏高',
    icon: '📉',
    category: '代谢湿浊',
    alias: ['高血压', '血压高', '头晕头痛', '肝阳上亢'],
    color: '#dc2626',
    summary: '血压偏高伴头晕头痛，食疗辅助调理，不能替代药物。',
    principle: '平肝清热、利湿降压，低盐低脂，控体重情绪。',
    ingredients: [
      { name: '芹菜', role: '平肝清热' },
      { name: '海带', role: '软坚利水' },
      { name: '玉米', role: '利水降压' },
      { name: '菊花', role: '平肝明目' },
      { name: '冬瓜', role: '利水消肿' },
    ],
    dishes: [
      { name: '芹菜汁', ingredients: '芹菜', note: '平肝降压，鲜榨少量' },
      { name: '芹菜红枣汤', ingredients: '芹菜、红枣', note: '养血平肝，头晕适用' },
      { name: '海带绿豆汤', ingredients: '海带、绿豆', note: '清热利湿，少油少盐' },
      { name: '玉米须茶', ingredients: '玉米须', note: '利水降压，代茶饮用' },
      { name: '冬瓜老鸭汤', ingredients: '冬瓜、鸭肉', note: '滋阴利水，夏季适用' },
    ],
    caution: '须遵医嘱服药监测；低血压慎芹菜汁；甲亢患者海带限量。',
    voiceTitle: '血压偏高：芹菜海带辅助调理',
    voiceSummary: '血压偏高食疗辅助，不能停药。芹菜汁、芹菜红枣汤、海带绿豆汤、玉米须茶、冬瓜老鸭汤，低盐低脂控体重。',
    voiceover: '血压高食疗只能辅助，药不能停。少量芹菜汁平肝；头晕炖芹菜红枣汤；海带绿豆汤利湿；泡玉米须茶；夏天冬瓜老鸭汤。低盐低脂控体重，按时测血压。',
  },

  血脂偏高: {
    name: '血脂偏高',
    icon: '🩸',
    category: '代谢湿浊',
    alias: ['高血脂', '血脂高', '胆固醇高', '痰湿内盛'],
    color: '#7c3aed',
    summary: '血脂胆固醇偏高，多与饮食不节、痰湿内盛相关。',
    principle: '消食化痰、利湿降脂，少油少糖，增运动。',
    ingredients: [
      { name: '山楂', role: '消食化瘀降脂' },
      { name: '海带', role: '软坚化痰' },
      { name: '茄子', role: '活血降脂' },
      { name: '黄瓜', role: '清热利水' },
      { name: '香菇', role: '扶正补虚、降脂辅助' },
    ],
    dishes: [
      { name: '山楂荷叶茶', ingredients: '山楂、荷叶', note: '消食降脂，代茶饮用' },
      { name: '海带豆腐汤', ingredients: '海带、豆腐', note: '清淡少油，日常汤品' },
      { name: '凉拌海带丝', ingredients: '海带', note: '消痰利水，少油凉拌' },
      { name: '山楂苹果饮', ingredients: '山楂、苹果', note: '消食化积，饭后温服' },
      { name: '蒜蓉蒸茄子', ingredients: '茄子、大蒜', note: '少油烹饪，活血消食' },
    ],
    caution: '须配合医嘱与复查；胃酸过多少山楂；甲亢限海带。',
    voiceTitle: '血脂偏高：山楂荷叶消食降脂',
    voiceSummary: '血脂高宜消食利湿。山楂荷叶茶、海带豆腐汤、凉拌海带丝、山楂苹果饮、蒜蓉蒸茄子，少油少糖多运动。',
    voiceover: '血脂高先管住嘴。泡山楂荷叶茶；海带豆腐汤清淡少油；凉拌海带丝消痰；饭后山楂苹果饮；茄子蒜蓉蒸少放油。配合复查医嘱，胃酸少喝山楂。',
  },

  消化不良: {
    name: '消化不良',
    icon: '🫃',
    category: '脾胃消化',
    alias: ['腹胀', '积食', '胃胀', '食积不化'],
    color: '#f59e0b',
    summary: '脘腹胀满、嗳气纳差，多见食积气滞或脾胃虚弱。',
    principle: '消食导滞、健脾和胃，少食多餐，忌暴饮暴食。',
    ingredients: [
      { name: '山楂', role: '消食化积' },
      { name: '白萝卜', role: '下气消食' },
      { name: '山药', role: '健脾和胃' },
      { name: '陈皮', role: '理气健脾' },
      { name: '小米', role: '和胃安神' },
    ],
    dishes: [
      { name: '山楂苹果饮', ingredients: '山楂、苹果', note: '消食化积，饭后温服' },
      { name: '萝卜排骨汤', ingredients: '白萝卜、排骨', note: '消食下气，荤腥吃多了' },
      { name: '小米山药粥', ingredients: '小米、山药', note: '健脾养胃，早餐温服' },
      { name: '陈皮普洱茶', ingredients: '陈皮、普洱', note: '理气消食，饭后温饮' },
      { name: '山药小米粥', ingredients: '山药、小米', note: '脾胃虚弱长期调理' },
    ],
    caution: '剧痛呕吐发热请就医；胃溃疡少食山楂；勿长期暴饮暴食。',
    voiceTitle: '消化不良：山楂萝卜消食导滞',
    voiceSummary: '腹胀积食先消食再健脾。山楂苹果饮、萝卜排骨汤、小米山药粥、陈皮普洱茶、山药小米粥，少食多餐。',
    voiceover: '吃多了胀肚子，先消食。饭后山楂苹果饮；荤腥吃多了炖萝卜排骨汤；脾虚长期熬小米山药粥；饭后泡陈皮普洱茶。剧痛呕吐发烧要看医生，别硬撑。',
  },

  食欲不振: {
    name: '食欲不振',
    icon: '🍽️',
    category: '脾胃消化',
    alias: ['没胃口', '纳差', '不思饮食', '厌食'],
    color: '#fb923c',
    summary: '食欲减退、食少纳呆，多见脾胃虚弱或湿阻中焦。',
    principle: '健脾开胃、理气化湿，清淡易消化，忌强迫进食。',
    ingredients: [
      { name: '番茄', role: '生津开胃' },
      { name: '山楂', role: '消食开胃' },
      { name: '陈皮', role: '理气健脾' },
      { name: '山药', role: '健脾益气' },
      { name: '鸭肉', role: '滋阴养胃' },
    ],
    dishes: [
      { name: '番茄鸡蛋汤', ingredients: '番茄、鸡蛋', note: '开胃营养，清淡易消化' },
      { name: '山楂陈皮茶', ingredients: '山楂、陈皮', note: '消食开胃，饭后温饮' },
      { name: '陈皮老鸭汤', ingredients: '陈皮、鸭肉', note: '理气开胃，暑湿困脾' },
      { name: '山药小米粥', ingredients: '山药、小米', note: '健脾开胃，早餐温服' },
      { name: '苹果山楂饮', ingredients: '苹果、山楂', note: '生津消食，儿童适用' },
    ],
    caution: '持续消瘦、发热需排查疾病；忌油腻辛辣；情志因素需调节。',
    voiceTitle: '食欲不振：番茄山楂开胃方',
    voiceSummary: '没胃口宜健脾开胃。番茄鸡蛋汤、山楂陈皮茶、陈皮老鸭汤、山药小米粥、苹果山楂饮，清淡少油。',
    voiceover: '没胃口别硬塞油腻。番茄鸡蛋汤开胃又营养；饭后山楂陈皮茶；暑湿困脾炖陈皮老鸭汤；脾虚熬山药小米粥；孩子试苹果山楂饮。持续消瘦要查因，心情也影响食欲。',
  },

  胃寒胃痛: {
    name: '胃寒胃痛',
    icon: '🤕',
    category: '脾胃消化',
    alias: ['胃痛', '胃脘冷痛', '胃寒', '喜温喜按'],
    color: '#57534e',
    summary: '胃脘冷痛、喜温喜按，进食生冷后加重。',
    principle: '温中散寒、和胃止痛，忌生冷冰饮，宜温热软烂。',
    ingredients: [
      { name: '生姜', role: '温中止痛' },
      { name: '糯米', role: '暖胃健脾' },
      { name: '红枣', role: '补中缓急' },
      { name: '羊肉', role: '温中补虚' },
      { name: '胡椒', role: '温中散寒（调味）' },
    ],
    dishes: [
      { name: '生姜红糖水', ingredients: '生姜、红糖', note: '温中散寒，胃痛畏寒' },
      { name: '糯米姜枣茶', ingredients: '糯米、生姜、红枣', note: '暖胃缓急，空腹温服' },
      { name: '当归生姜羊肉汤', ingredients: '当归、生姜、羊肉', note: '温中补血，虚寒胃痛' },
      { name: '南瓜小米粥', ingredients: '南瓜、小米', note: '温中益气，胃寒调养' },
      { name: '胡椒猪肚汤', ingredients: '猪肚、胡椒、生姜', note: '温中暖胃，慢性胃寒' },
    ],
    caution: '剧痛、呕血、黑便立即就医；胃溃疡遵医嘱；忌生冷冰饮。',
    voiceTitle: '胃寒胃痛：生姜红糖温中',
    voiceSummary: '胃寒宜温中。生姜红糖水、糯米姜枣茶、当归生姜羊肉汤、南瓜小米粥、胡椒猪肚汤，忌生冷冰饮。',
    voiceover: '胃怕冷一吃凉就痛，要温中。喝生姜红糖水；糯米姜枣茶暖胃；虚寒重炖当归生姜羊肉汤；日常南瓜小米粥；慢性胃寒煲胡椒猪肚汤。剧痛呕血黑便立刻就医。',
  },

  贫血: {
    name: '贫血',
    icon: '🩸',
    category: '气血虚寒',
    alias: ['血虚', '面色萎黄', '头晕眼花', '缺铁性贫血'],
    color: '#be123c',
    summary: '面色萎黄、头晕心悸，多见血虚或铁摄入不足。',
    principle: '益气养血、补肝益肾，搭配富含铁食物，遵医嘱补铁。',
    ingredients: [
      { name: '红枣', role: '养血安神' },
      { name: '菠菜', role: '养血润燥' },
      { name: '排骨', role: '滋阴补虚、煲汤养血' },
      { name: '桂圆', role: '补血养心' },
      { name: '花生', role: '养血止血' },
    ],
    dishes: [
      { name: '菠菜猪肝汤', ingredients: '菠菜、猪肝', note: '养血明目，适量食用' },
      { name: '红枣花生粥', ingredients: '红枣、花生、大米', note: '健脾养血，早餐温服' },
      { name: '当归鸡蛋汤', ingredients: '当归、鸡蛋', note: '养血调经，女性调养' },
      { name: '桂圆红枣茶', ingredients: '桂圆、红枣', note: '补血安神，日常温饮' },
      { name: '猪肝枸杞汤', ingredients: '猪肝、枸杞', note: '补肝明目，血虚眼花' },
    ],
    caution: '严重贫血须医嘱补铁；猪肝不宜过量；孕妇贫血遵医嘱。',
    voiceTitle: '贫血食疗：红枣菠菜猪肝养血',
    voiceSummary: '贫血宜益气养血。菠菜猪肝汤、红枣花生粥、当归鸡蛋汤、桂圆红枣茶、猪肝枸杞汤，遵医嘱补铁复查。',
    voiceover: '头晕脸色黄，补血要搭配。菠菜猪肝汤适量；早餐红枣花生粥；女性炖当归鸡蛋汤；日常桂圆红枣茶；眼花加枸杞猪肝汤。严重贫血听医生的，猪肝别过量。',
  },

  产后体虚: {
    name: '产后体虚',
    icon: '👶',
    category: '气血虚寒',
    alias: ['产后调养', '月子餐', '产后虚弱', '产后恢复'],
    color: '#f472b6',
    summary: '产后气血耗伤、乏力畏寒，需温补缓补，循序渐进。',
    principle: '益气补血、温中健脾，清淡温补，忌生冷辛辣。',
    ingredients: [
      { name: '鸡肉', role: '温中益气' },
      { name: '桂圆', role: '补血安神' },
      { name: '红枣', role: '补中益气' },
      { name: '鲫鱼', role: '和中补虚' },
      { name: '山药', role: '健脾益气' },
    ],
    dishes: [
      { name: '老母鸡汤', ingredients: '老母鸡', note: '大补元气，产后第二周起' },
      { name: '桂圆小米粥', ingredients: '桂圆、小米', note: '补血安神，易消化' },
      { name: '当归黄芪炖鸡', ingredients: '当归、黄芪、鸡肉', note: '气血双补，遵医嘱' },
      { name: '鲫鱼豆腐汤', ingredients: '鲫鱼、豆腐', note: '补虚通乳，清淡少油' },
      { name: '山药排骨汤', ingredients: '山药、排骨', note: '健脾补气，病后调养' },
    ],
    caution: '发热、感染、乳腺炎请就医；剖腹产遵医嘱进食；忌大补过早。',
    voiceTitle: '产后体虚：鸡汤鲫鱼温补缓补',
    voiceSummary: '产后宜温补缓补。老母鸡汤、桂圆小米粥、当归黄芪炖鸡、鲫鱼豆腐汤、山药排骨汤，循序渐进忌生冷。',
    voiceover: '产后调养别急补猛补。第二周起炖老母鸡汤；桂圆小米粥易消化；气血虚煲当归黄芪炖鸡；鲫鱼豆腐汤补虚通乳；山药排骨汤健脾。发烧感染乳腺炎要看医生。',
  },

  产后缺乳: {
    name: '产后缺乳',
    icon: '🍼',
    category: '气血虚寒',
    alias: ['奶水不足', '乳汁不下', '缺乳', '催乳'],
    color: '#fda4af',
    summary: '产后乳汁稀少或不下，多与气血不足、肝郁气滞有关。',
    principle: '补气养血、通络下乳，保持情绪舒畅，多让宝宝吸吮。',
    ingredients: [
      { name: '排骨', role: '滋阴补虚、煲汤催乳' },
      { name: '黄豆', role: '健脾催乳' },
      { name: '鲫鱼', role: '通乳补虚' },
      { name: '花生', role: '养血通乳' },
      { name: '虾仁', role: '补肾通乳' },
    ],
    dishes: [
      { name: '猪蹄黄豆汤', ingredients: '猪蹄、黄豆', note: '经典催乳方，产后调养' },
      { name: '鲫鱼豆腐汤', ingredients: '鲫鱼、豆腐', note: '通乳补虚，清淡少油' },
      { name: '花生猪蹄汤', ingredients: '花生、猪蹄', note: '养血通乳，适量' },
      { name: '虾仁豆腐羹', ingredients: '虾仁、豆腐', note: '通乳益气，易消化' },
      { name: '木瓜鲫鱼汤', ingredients: '木瓜、鲫鱼', note: '民间通乳搭配，适量' },
    ],
    caution: '乳腺炎、发热禁盲目催乳；乳房硬块及时就医；忌回奶食物如韭菜大量。',
    voiceTitle: '产后缺乳：猪蹄黄豆鲫鱼通乳',
    voiceSummary: '缺乳宜补气通乳。猪蹄黄豆汤、鲫鱼豆腐汤、花生猪蹄汤、虾仁豆腐羹，保持吸吮情绪舒畅。',
    voiceover: '奶水少先补气通乳。炖猪蹄黄豆汤；清淡鲫鱼豆腐汤；加花生炖猪蹄汤；虾仁豆腐羹易消化。让宝宝多吸吮，保持心情好。乳房红肿发烧是乳腺炎，要就医。',
  },

  月经不调: {
    name: '月经不调',
    icon: '📅',
    category: '气血虚寒',
    alias: ['月经紊乱', '经期不准', '月经量少', '周期失调'],
    color: '#e879f9',
    summary: '周期紊乱、经量异常，需辨证，食疗辅助调理。',
    principle: '补血活血、疏肝理气，规律作息，忌生冷寒凉。',
    ingredients: [
      { name: '当归', role: '补血调经' },
      { name: '红枣', role: '养血安神' },
      { name: '桂圆', role: '补血养心' },
      { name: '生姜', role: '温经散寒' },
      { name: '玫瑰花', role: '疏肝理气' },
    ],
    dishes: [
      { name: '当归红枣鸡汤', ingredients: '当归、红枣、鸡肉', note: '补血调经，经期后调养' },
      { name: '红糖姜茶', ingredients: '红糖、生姜', note: '温经散寒，经寒腹痛' },
      { name: '桂圆红枣茶', ingredients: '桂圆、红枣', note: '养血安神，量少色淡' },
      { name: '玫瑰花茶', ingredients: '玫瑰花', note: '疏肝理气，情志不畅' },
      { name: '当归鸡蛋汤', ingredients: '当归、鸡蛋', note: '养血调经，日常调养' },
    ],
    caution: '异常出血、闭经六月以上请就医；孕期忌活血食材；遵医嘱。',
    voiceTitle: '月经不调：当归红枣温经养血',
    voiceSummary: '月经不调宜养血疏肝。当归红枣鸡汤、红糖姜茶、桂圆红枣茶、玫瑰花茶、当归鸡蛋汤，经期忌生冷。',
    voiceover: '月经不准要辨证调理。经期后炖当归红枣鸡汤；经寒腹痛喝红糖姜茶；量少喝桂圆红枣茶；心情不好泡玫瑰花茶；日常当归鸡蛋汤。大出血闭经要看医生，孕期别乱活血。',
  },

  痛经: {
    name: '痛经',
    icon: '😣',
    category: '气血虚寒',
    alias: ['经期腹痛', '经痛', '寒凝血瘀', '痛经'],
    color: '#db2777',
    summary: '经期小腹疼痛，分寒凝、气滞、血瘀，食疗以温经为主。',
    principle: '温经散寒、活血止痛，经期保暖，忌生冷冰饮。',
    ingredients: [
      { name: '生姜', role: '温经散寒' },
      { name: '当归', role: '补血活血' },
      { name: '桂圆', role: '温补气血' },
      { name: '山楂', role: '活血散瘀' },
      { name: '羊肉', role: '温中补虚' },
    ],
    dishes: [
      { name: '红糖姜茶', ingredients: '红糖、生姜', note: '温经止痛，经期温服' },
      { name: '当归生姜羊肉汤', ingredients: '当归、生姜、羊肉', note: '温经补血，寒凝血瘀' },
      { name: '山楂红糖水', ingredients: '山楂、红糖', note: '活血散瘀，经后瘀痛' },
      { name: '桂圆姜枣茶', ingredients: '桂圆、生姜、红枣', note: '温补气血，虚寒痛经' },
      { name: '艾叶鸡蛋汤', ingredients: '艾叶、鸡蛋', note: '温经散寒，遵医嘱适量' },
    ],
    caution: '剧痛、经血过多请就医；继发性痛经需查因；经期忌生冷。',
    voiceTitle: '痛经：红糖姜茶温经止痛',
    voiceSummary: '痛经宜温经散寒。红糖姜茶、当归生姜羊肉汤、山楂红糖水、桂圆姜枣茶，经期保暖忌生冷冰饮。',
    voiceover: '痛经别喝冰的。经期温服红糖姜茶；虚寒重炖当归生姜羊肉汤；瘀痛经后试山楂红糖水；平时泡桂圆姜枣茶。剧痛经血多要看医生，查明是不是继发痛经。',
  },

  更年期烦躁: {
    name: '更年期烦躁',
    icon: '🌡️',
    category: '睡眠情志',
    alias: ['更年期', '潮热盗汗', '烦躁失眠', '围绝经期'],
    color: '#a855f7',
    summary: '潮热盗汗、烦躁失眠，多见阴虚火旺、心肾不交。',
    principle: '滋阴清热、养心安神，规律作息，少辛辣燥热。',
    ingredients: [
      { name: '百合', role: '清心安神' },
      { name: '莲子', role: '养心安神' },
      { name: '银耳', role: '滋阴润肺' },
      { name: '枸杞', role: '滋补肝肾' },
      { name: '小麦', role: '养心安神' },
    ],
    dishes: [
      { name: '百合莲子羹', ingredients: '百合、莲子', note: '清心安神，烦躁失眠' },
      { name: '甘麦大枣汤', ingredients: '甘草、小麦、红枣', note: '养心安神，悲伤烦躁' },
      { name: '银耳枸杞羹', ingredients: '银耳、枸杞', note: '滋阴润燥，潮热口干' },
      { name: '莲子百合粥', ingredients: '莲子、百合、小米', note: '安神助眠，晚间温服' },
      { name: '山药百合羹', ingredients: '山药、百合', note: '润肺健脾，阴虚调养' },
    ],
    caution: '症状严重影响生活请就医；激素治疗遵医嘱；保持运动社交。',
    voiceTitle: '更年期烦躁：百合莲子滋阴安神',
    voiceSummary: '更年期宜滋阴安神。百合莲子羹、甘麦大枣汤、银耳枸杞羹、莲子百合粥，少辛辣规律作息。',
    voiceover: '更年期潮热烦躁，滋阴安神是关键。炖百合莲子羹；情志差参考甘麦大枣汤；口干潮热煮银耳枸杞羹；睡前莲子百合粥。严重影响生活要看医生，别硬扛。',
  },

  焦虑抑郁: {
    name: '焦虑抑郁',
    icon: '😔',
    category: '睡眠情志',
    alias: ['焦虑', '抑郁', '情绪低落', '心烦不安'],
    color: '#64748b',
    summary: '情绪低落、焦虑不安，食疗辅助，需重视心理健康。',
    principle: '疏肝理气、养心安神，规律作息，必要时专业干预。',
    ingredients: [
      { name: '小麦', role: '养心安神' },
      { name: '红枣', role: '补中益气' },
      { name: '百合', role: '清心安神' },
      { name: '玫瑰花', role: '疏肝解郁' },
      { name: '桂圆', role: '补血安神' },
    ],
    dishes: [
      { name: '甘麦大枣汤', ingredients: '甘草、小麦、红枣', note: '经典安神方，悲伤哭泣' },
      { name: '玫瑰花茶', ingredients: '玫瑰花', note: '疏肝解郁，日常温饮' },
      { name: '百合莲子粥', ingredients: '百合、莲子', note: '清心安神，失眠烦躁' },
      { name: '桂圆红枣茶', ingredients: '桂圆、红枣', note: '养血安神，乏力情绪低落' },
      { name: '小麦红枣粥', ingredients: '小麦、红枣', note: '养心缓急，情志失调' },
    ],
    caution: '中重度抑郁焦虑请专业治疗；食疗不能替代药物；有自伤念头立即求助。',
    voiceTitle: '焦虑抑郁：甘麦大枣疏肝安神',
    voiceSummary: '情志问题食疗辅助。甘麦大枣汤、玫瑰花茶、百合莲子粥、桂圆红枣茶，必要时寻求专业帮助。',
    voiceover: '情绪低落焦虑，食疗只能辅助。悲伤不安参考甘麦大枣汤；泡玫瑰花茶疏肝；失眠烦躁煮百合莲子粥；乏力喝桂圆红枣茶。中重度要专业治疗，有自伤念头立刻求助。',
  },

  口腔溃疡: {
    name: '口腔溃疡',
    icon: '👄',
    category: '肤发骨质',
    alias: ['口疮', '上火口疮', '口舌生疮', '口腔溃疡'],
    color: '#f43f5e',
    summary: '口腔黏膜溃疡疼痛，多见心脾积热或阴虚火旺。',
    principle: '清热泻火、滋阴生津，忌辛辣烧烤，保持口腔卫生。',
    ingredients: [
      { name: '菊花', role: '清热解毒' },
      { name: '绿豆', role: '清热解毒' },
      { name: '梨', role: '生津润燥' },
      { name: '苦瓜', role: '清热降火' },
      { name: '蜂蜜', role: '润燥解毒' },
    ],
    dishes: [
      { name: '菊花茶', ingredients: '菊花', note: '清热降火，代茶饮用' },
      { name: '绿豆汤', ingredients: '绿豆', note: '清热解毒，暑热火盛' },
      { name: '冰糖雪梨汤', ingredients: '雪梨、冰糖', note: '生津润燥，咽干口燥' },
      { name: '凉拌苦瓜', ingredients: '苦瓜', note: '清热降火，少量食用' },
      { name: '蜂蜜柠檬水', ingredients: '蜂蜜、柠檬', note: '生津润燥，晨起少量' },
    ],
    caution: '反复发作、久不愈合请就医；忌辛辣烟酒；孕妇苦瓜适量。',
    voiceTitle: '口腔溃疡：菊花绿豆清热',
    voiceSummary: '口疮宜清热生津。菊花茶、绿豆汤、冰糖雪梨汤、凉拌苦瓜、蜂蜜柠檬水，忌辛辣保持口腔卫生。',
    voiceover: '口腔溃疡疼，先清热生津。泡菊花茶；煮绿豆汤；炖冰糖雪梨汤；少量凉拌苦瓜；晨起蜂蜜柠檬水。反复发作久不愈要看医生，忌辛辣烟酒。',
  },

  脱发: {
    name: '脱发',
    icon: '💇',
    category: '肤发骨质',
    alias: ['掉发', '须发早白', '脱发增多', '血虚脱发'],
    color: '#1e293b',
    summary: '脱发增多、须发早白，多与血虚、肾虚或压力过大相关。',
    principle: '补血益肾、润燥养发，规律作息，减少熬夜压力。',
    ingredients: [
      { name: '黑芝麻', role: '补肝肾润肠' },
      { name: '核桃', role: '补肾益精' },
      { name: '黑豆', role: '补肾益阴' },
      { name: '枸杞', role: '滋补肝肾' },
      { name: '山药', role: '补脾益肾、乌发辅助' },
    ],
    dishes: [
      { name: '黑芝麻糊', ingredients: '黑芝麻', note: '补肝肾乌发，早餐温服' },
      { name: '核桃芝麻粥', ingredients: '核桃、黑芝麻、大米', note: '健脑补肾，日常调养' },
      { name: '黑豆核桃粥', ingredients: '黑豆、核桃', note: '补肾益精，早餐温服' },
      { name: '枸杞山药粥', ingredients: '枸杞、山药', note: '平补脾肾，须发早白' },
      { name: '桑葚粥', ingredients: '桑葚、大米', note: '滋阴补血，脱发调养' },
    ],
    caution: '突然大面积脱发、斑秃请就医；食疗需坚持；排查甲状腺等问题。',
    voiceTitle: '脱发：黑芝麻黑豆补肾养发',
    voiceSummary: '脱发宜补血益肾。黑芝麻糊、核桃芝麻粥、黑豆核桃粥、枸杞山药粥，规律作息少熬夜。',
    voiceover: '掉发多、头发早白，补肾养血要坚持。早餐黑芝麻糊；核桃芝麻粥日常吃；黑豆核桃粥补肾；枸杞山药粥平补。突然大面积脱发要看医生，别只靠食疗。',
  },

  痤疮粉刺: {
    name: '痤疮粉刺',
    icon: '😤',
    category: '肤发骨质',
    alias: ['痘痘', '青春痘', '粉刺', '肺胃热盛'],
    color: '#ef4444',
    summary: '面部痤疮粉刺，多见肺胃湿热、血热瘀滞。',
    principle: '清热利湿、凉血解毒，少油腻辛辣甜食，清洁护肤。',
    ingredients: [
      { name: '绿豆', role: '清热解毒' },
      { name: '薏米', role: '健脾渗湿' },
      { name: '冬瓜', role: '清热利水' },
      { name: '黄瓜', role: '清热解毒' },
      { name: '海带', role: '软坚化痰' },
    ],
    dishes: [
      { name: '绿豆薏米粥', ingredients: '绿豆、薏米', note: '清热祛湿，少糖' },
      { name: '海带绿豆汤', ingredients: '海带、绿豆', note: '清热解毒，夏季适用' },
      { name: '冬瓜荷叶茶', ingredients: '冬瓜、荷叶', note: '清热利湿，代茶饮用' },
      { name: '凉拌黄瓜', ingredients: '黄瓜', note: '清热开胃，少油凉拌' },
      { name: '薏米红豆汤', ingredients: '薏米、红豆', note: '祛湿消肿，湿热痤疮' },
    ],
    caution: '严重囊肿痤疮请皮肤科就诊；忌挤痘；乳制品高糖可能加重。',
    voiceTitle: '痤疮粉刺：绿豆薏米清热祛湿',
    voiceSummary: '痘痘宜清热祛湿。绿豆薏米粥、海带绿豆汤、冬瓜荷叶茶、凉拌黄瓜，少油腻辛辣甜食。',
    voiceover: '长痘多是湿热，饮食要清爽。熬绿豆薏米粥；海带绿豆汤清热；泡冬瓜荷叶茶；凉拌黄瓜少放油。严重囊肿痘要看皮肤科，别乱挤。',
  },

  水肿浮肿: {
    name: '水肿浮肿',
    icon: '🦶',
    category: '代谢湿浊',
    alias: ['浮肿', '水肿', '小便不利', '湿气水肿'],
    color: '#06b6d4',
    summary: '眼睑下肢浮肿、小便不利，多见水湿内停。',
    principle: '健脾利湿、利水消肿，低盐饮食，监测心肾功能。',
    ingredients: [
      { name: '冬瓜', role: '利水消肿' },
      { name: '薏米', role: '健脾渗湿' },
      { name: '红豆', role: '利水解毒' },
      { name: '玉米', role: '利水降压' },
      { name: '茯苓', role: '利水渗湿' },
    ],
    dishes: [
      { name: '冬瓜薏米汤', ingredients: '冬瓜、薏米', note: '健脾利湿，少盐' },
      { name: '红豆薏米汤', ingredients: '红豆、薏米', note: '经典祛湿消肿' },
      { name: '玉米须茶', ingredients: '玉米须', note: '利水消肿，代茶饮用' },
      { name: '冬瓜老鸭汤', ingredients: '冬瓜、鸭肉', note: '滋阴利水，夏季适用' },
      { name: '茯苓山药粥', ingredients: '茯苓、山药', note: '健脾祛湿，早餐温服' },
    ],
    caution: '突发水肿、伴胸闷气短立即就医；心肾疾病遵医嘱；低盐限水遵医嘱。',
    voiceTitle: '水肿浮肿：冬瓜薏米利水',
    voiceSummary: '水肿宜健脾利水。冬瓜薏米汤、红豆薏米汤、玉米须茶、冬瓜老鸭汤，低盐饮食监测心肾。',
    voiceover: '眼皮腿肿小便少，先利水祛湿。煮冬瓜薏米汤；红豆薏米汤经典；泡玉米须茶；夏天冬瓜老鸭汤。突然肿伴胸闷气短立刻就医，心肾病听医生限盐限水。',
  },

  糖尿病调理: {
    name: '糖尿病调理',
    icon: '🍬',
    category: '代谢湿浊',
    alias: ['高血糖', '消渴', '糖尿病食疗', '血糖高'],
    color: '#84cc16',
    summary: '血糖偏高辅助食疗，必须配合医嘱用药与监测。',
    principle: '益气养阴、健脾祛湿，低糖低GI，控量分餐，遵医嘱。',
    ingredients: [
      { name: '山药', role: '健脾益肾、辅助降糖' },
      { name: '南瓜', role: '补中益气（控量）' },
      { name: '苦瓜', role: '清热降血糖脂' },
      { name: '薏米', role: '健脾渗湿' },
      { name: '黑木耳', role: '润燥活血' },
    ],
    dishes: [
      { name: '山药小米粥', ingredients: '山药、小米', note: '健脾养胃，早餐控量' },
      { name: '苦瓜炒鸡蛋', ingredients: '苦瓜、鸡蛋', note: '清热开胃，适量佐餐' },
      { name: '薏米山药粥', ingredients: '薏米、山药', note: '健脾祛湿，少糖' },
      { name: '凉拌黑木耳', ingredients: '黑木耳', note: '润燥活血，少油凉拌' },
      { name: '南瓜小米粥', ingredients: '南瓜、小米', note: '控量食用，监测血糖' },
    ],
    caution: '绝不能替代降糖药；粥类升糖快需控量；定期监测遵医嘱。',
    voiceTitle: '糖尿病调理：山药苦瓜辅助控糖',
    voiceSummary: '糖尿病食疗仅辅助，药不能停。山药小米粥、苦瓜炒鸡蛋、薏米山药粥，低糖低GI控量分餐。',
    voiceover: '血糖高食疗只能帮忙，药和监测不能停。早餐山药小米粥要控量；苦瓜炒鸡蛋清热；薏米山药粥健脾祛湿；南瓜粥更要看血糖。粥升糖快，每次吃完测一下。',
  },

  骨质疏松: {
    name: '骨质疏松',
    icon: '🦴',
    category: '肤发骨质',
    alias: ['缺钙', '骨密度低', '腰酸腿软', '骨质疏松'],
    color: '#94a3b8',
    summary: '骨密度降低、易骨折，需补钙维D、运动与医嘱。',
    principle: '补肾壮骨、补钙益精，日晒运动，遵医嘱补钙。',
    ingredients: [
      { name: '紫菜', role: '补肾养心、搭配虾皮补钙' },
      { name: '紫菜', role: '补肾养心' },
      { name: '黑芝麻', role: '补肝肾益精' },
      { name: '核桃', role: '补肾强骨' },
      { name: '排骨', role: '滋阴补钙（汤）' },
    ],
    dishes: [
      { name: '紫菜虾皮汤', ingredients: '紫菜、虾皮', note: '补钙益气，日常汤品' },
      { name: '虾仁豆腐羹', ingredients: '虾仁、豆腐', note: '高蛋白补钙，清淡' },
      { name: '排骨玉米汤', ingredients: '排骨、玉米', note: '补钙补虚，撇油煲汤' },
      { name: '黑芝麻核桃糊', ingredients: '黑芝麻、核桃', note: '补肝肾壮骨' },
      { name: '黑豆核桃粥', ingredients: '黑豆、核桃', note: '补肾益精，早餐温服' },
    ],
    caution: '须医嘱补钙维D；肾结石患者遵医嘱；防跌倒运动。',
    voiceTitle: '骨质疏松：虾皮豆腐补钙壮骨',
    voiceSummary: '骨质疏松宜补肾补钙。紫菜虾皮汤、虾仁豆腐羹、排骨玉米汤、黑芝麻核桃糊，日晒运动遵医嘱补钙。',
    voiceover: '骨密度低要补钙补肾还要动。紫菜虾皮汤平价补钙；虾仁豆腐羹清淡；排骨玉米汤撇油煲；黑芝麻核桃糊日常吃。补钙维D听医生的，多晒太阳防跌倒。',
  },

  免疫力低下: {
    name: '免疫力低下',
    icon: '🛡️',
    category: '肾腰免疫',
    alias: ['易感冒', '体质差', '抵抗力弱', '反复感冒'],
    color: '#10b981',
    summary: '反复感冒、乏力易病，多见气虚卫外不固。',
    principle: '益气固表、健脾补肾，规律作息，适度运动。',
    ingredients: [
      { name: '排骨', role: '滋阴补虚、煲汤益气' },
      { name: '鸡肉', role: '温中益气' },
      { name: '香菇', role: '扶正补虚' },
      { name: '山药', role: '健脾益气' },
      { name: '红枣', role: '补中益气' },
    ],
    dishes: [
      { name: '黄芪炖鸡', ingredients: '黄芪、鸡肉', note: '益气固表，易感冒适用' },
      { name: '香菇鸡汤', ingredients: '香菇、鸡肉', note: '扶正补虚，病后调养' },
      { name: '山药排骨汤', ingredients: '山药、排骨', note: '健脾益气，增强体质' },
      { name: '红枣山药粥', ingredients: '红枣、山药', note: '补气健脾，早餐温服' },
      { name: '香菇排骨粥', ingredients: '香菇、排骨、大米', note: '益气补血，日常调养' },
    ],
    caution: '持续发热、体重下降请排查；急性感染期忌大补；过敏者慎香菇。',
    voiceTitle: '免疫力低：黄芪香菇益气固表',
    voiceSummary: '易感冒宜益气固表。黄芪炖鸡、香菇鸡汤、山药排骨汤、红枣山药粥，规律作息适度运动。',
    voiceover: '总感冒是卫气不足。炖黄芪炖鸡固表；香菇鸡汤扶正补虚；山药排骨汤健脾；早餐红枣山药粥。发烧感染期别大补，持续消瘦要查因。',
  },

  风热感冒: {
    name: '风热感冒',
    icon: '🤒',
    category: '呼吸外感',
    alias: ['风热', '黄痰感冒', '咽痛发热', '风热外感'],
    color: '#f97316',
    summary: '发热重、微恶风、咽痛、咳黄痰、口渴，属风热犯肺。',
    principle: '辛凉解表、清热宣肺，宜清淡多汁，忌辛辣温补。',
    ingredients: [
      { name: '梨', role: '清热润燥、化痰' },
      { name: '菊花', role: '疏散风热、清肝' },
      { name: '绿豆', role: '清热解毒' },
      { name: '薄荷', role: '疏散风热（少量）' },
      { name: '白萝卜', role: '化痰下气' },
    ],
    dishes: [
      { name: '冰糖雪梨汤', ingredients: '雪梨、冰糖', note: '清热润肺，咽干咳嗽' },
      { name: '菊花薄荷茶', ingredients: '菊花、薄荷', note: '辛凉解表，少量温饮' },
      { name: '绿豆汤', ingredients: '绿豆', note: '清热解毒，暑热风热' },
      { name: '盐蒸橙子', ingredients: '橙子、盐', note: '化痰润喉，风热咳嗽' },
      { name: '萝卜蜂蜜饮', ingredients: '白萝卜、蜂蜜', note: '润肺化痰，痰黄黏稠' },
    ],
    caution: '恶寒重、清涕、无汗多属风寒，忌过用寒凉；高热不退请就医。',
    voiceTitle: '风热感冒：梨汤菊花茶辛凉解表',
    voiceSummary: '风热宜辛凉清热。冰糖雪梨汤、菊花薄荷茶、绿豆汤、盐蒸橙子，忌温补生姜羊肉。',
    voiceover: '发烧咽痛、咳黄痰，多是风热感冒。炖冰糖雪梨汤；泡菊花薄荷茶；煮绿豆汤清热；盐蒸橙子润喉。恶寒重清涕是风寒，别乱用寒凉，高热要看医生。',
  },

  暑热中暑: {
    name: '暑热中暑',
    icon: '☀️',
    category: '呼吸外感',
    alias: ['中暑', '暑湿', '头晕乏力', '夏日中暑'],
    color: '#eab308',
    summary: '暑热季节头晕乏力、恶心口渴、汗多胸闷，属暑湿伤津。',
    principle: '清热解暑、益气生津，及时补水，移至阴凉处。',
    ingredients: [
      { name: '绿豆', role: '清热解毒' },
      { name: '冬瓜', role: '清热利水' },
      { name: '黄瓜', role: '清热利水' },
      { name: '百合', role: '清心润燥' },
      { name: '薏米', role: '健脾利湿' },
    ],
    dishes: [
      { name: '绿豆汤', ingredients: '绿豆、冰糖', note: '清热解毒，中暑初期温服' },
      { name: '冬瓜薏米汤', ingredients: '冬瓜、薏米', note: '清热利湿，暑湿困重' },
      { name: '荷叶冬瓜茶', ingredients: '荷叶、冬瓜皮', note: '解暑生津，代茶饮用' },
      { name: '西瓜翠衣饮', ingredients: '西瓜皮', note: '清热解暑，少量频饮' },
      { name: '绿豆百合汤', ingredients: '绿豆、百合', note: '清心润燥，烦热口渴' },
    ],
    caution: '意识模糊、高热不退立即送医；脾胃虚寒少饮寒凉；剧烈运动后忌猛灌冰水。',
    voiceTitle: '暑热中暑：绿豆汤冬瓜汤解暑',
    voiceSummary: '中暑先清热解暑补水。绿豆汤、冬瓜薏米汤、荷叶茶、西瓜翠衣饮，移至阴凉及时就医。',
    voiceover: '夏天头晕恶心口渴，要防中暑。煮绿豆汤清热解毒；冬瓜薏米汤祛暑湿；泡荷叶茶；西瓜皮煎水频饮。意识不清高热立刻送医，别猛灌冰水。',
  },

  反酸烧心: {
    name: '反酸烧心',
    icon: '🔥',
    category: '脾胃消化',
    alias: ['胃酸过多', '胃食管反流', '烧心', '泛酸'],
    color: '#dc2626',
    summary: '胃酸上逆、烧心嗳气，多见肝胃不和、胃热灼盛。',
    principle: '和胃降逆、清热制酸，少食多餐，忌咖啡酒精辛辣。',
    ingredients: [
      { name: '山药', role: '健脾和胃' },
      { name: '小米', role: '和胃安神' },
      { name: '南瓜', role: '补中益气、护胃' },
      { name: '生姜', role: '和胃止呕（少量）' },
      { name: '白菜', role: '养胃生津' },
    ],
    dishes: [
      { name: '山药小米粥', ingredients: '山药、小米', note: '健脾养胃，早餐温服' },
      { name: '蒸南瓜泥', ingredients: '南瓜', note: '护胃易消化，少量多餐' },
      { name: '白菜豆腐汤', ingredients: '白菜、豆腐', note: '清热养胃，清淡少油' },
      { name: '大米粥', ingredients: '大米', note: '养胃制酸，煮出米油' },
      { name: '生姜大枣茶', ingredients: '生姜、红枣', note: '和胃缓急，胃寒反酸' },
    ],
    caution: '持续胸痛、吞咽困难、黑便请就医；睡前两小时不进食；肥胖者减重有助缓解。',
    voiceTitle: '反酸烧心：山药小米养胃制酸',
    voiceSummary: '反酸宜和胃制酸。山药小米粥、蒸南瓜泥、白菜豆腐汤、大米粥，忌咖啡辛辣睡前饱食。',
    voiceover: '烧心泛酸，先养胃黏膜。熬山药小米粥；吃蒸南瓜泥；炖白菜豆腐汤；大米粥煮出米油。咖啡酒精辛辣睡前别吃，胸痛黑便要看医生。',
  },

  口臭: {
    name: '口臭',
    icon: '👄',
    category: '肤发骨质',
    alias: ['口气重', '口腔异味', '口臭口苦', '口气大'],
    color: '#84cc16',
    summary: '口气异味，多见胃热积滞、食积不化或口腔卫生问题。',
    principle: '清热和胃、消食化滞，口腔清洁，忌烟酒厚味。',
    ingredients: [
      { name: '菊花', role: '清热解毒' },
      { name: '绿豆', role: '清热降火' },
      { name: '山楂', role: '消食化积' },
      { name: '陈皮', role: '理气健脾' },
      { name: '芹菜', role: '清热利湿' },
    ],
    dishes: [
      { name: '菊花茶', ingredients: '菊花', note: '清热降火，代茶饮用' },
      { name: '绿豆汤', ingredients: '绿豆', note: '清热解毒，胃热口臭' },
      { name: '山楂陈皮茶', ingredients: '山楂、陈皮', note: '消食化滞，肉食后口臭' },
      { name: '芹菜汁', ingredients: '芹菜', note: '清热利湿，少量鲜榨' },
      { name: '薄荷绿茶', ingredients: '绿茶、薄荷', note: '清新口气，饭后漱口' },
    ],
    caution: '牙周病、幽门螺杆菌、糖尿病等需排查；坚持刷牙漱口牙线；口臭持续请口腔科。',
    voiceTitle: '口臭：菊花山楂消食清热',
    voiceSummary: '口臭多清胃消食。菊花茶、绿豆汤、山楂陈皮茶，口腔清洁忌烟酒，持续异味要查因。',
    voiceover: '口气重先查口腔和胃热。泡菊花茶；煮绿豆汤；肉食后山楂陈皮茶；芹菜汁少量鲜榨。刷牙漱口别偷懒，口臭一直不好要看牙医查幽门螺杆菌。',
  },

  肥胖减重: {
    name: '肥胖减重',
    icon: '⚖️',
    category: '代谢湿浊',
    alias: ['减肥', '超重', '痰湿肥胖', '体重管理'],
    color: '#0d9488',
    summary: '体重超标、痰湿内盛，食疗辅助控脂祛湿，需配合运动作息。',
    principle: '健脾祛湿、消食导滞、低脂少糖，循序渐进，忌节食过猛。',
    ingredients: [
      { name: '薏米', role: '健脾渗湿' },
      { name: '冬瓜', role: '利水消肿' },
      { name: '山楂', role: '消食化瘀' },
      { name: '黄瓜', role: '清热利水' },
      { name: '海带', role: '软坚化痰' },
    ],
    dishes: [
      { name: '薏米红豆汤', ingredients: '薏米、红豆', note: '祛湿消肿，少糖' },
      { name: '冬瓜荷叶茶', ingredients: '冬瓜、荷叶', note: '清热利湿，代茶饮用' },
      { name: '山楂荷叶茶', ingredients: '山楂、荷叶', note: '消食降脂，饭后温饮' },
      { name: '凉拌黄瓜', ingredients: '黄瓜', note: '低卡开胃，少油凉拌' },
      { name: '海带豆腐汤', ingredients: '海带、豆腐', note: '清淡少油，日常汤品' },
    ],
    caution: 'BMI过高、合并糖尿病高血压请医嘱管理；孕妇哺乳期不宜猛减；配合运动才长久。',
    voiceTitle: '肥胖减重：薏米冬瓜祛湿控脂',
    voiceSummary: '减重宜祛湿低脂。薏米红豆汤、冬瓜荷叶茶、山楂荷叶茶，少糖少油配合运动。',
    voiceover: '想健康减重，祛湿低脂是关键。薏米红豆汤少糖；泡冬瓜荷叶茶；饭后山楂荷叶茶；凉拌黄瓜低卡。别节食过猛，配合运动才长久，有病要听医生的。',
  },

  痛风: {
    name: '痛风',
    icon: '🦶',
    category: '代谢湿浊',
    alias: ['尿酸高', '痛风发作', '关节红肿', '高尿酸'],
    color: '#7c3aed',
    summary: '尿酸偏高、关节红肿热痛，急性期需医嘱，食疗重在平素调理。',
    principle: '利湿浊、少嘌呤、多饮水，忌海鲜啤酒内脏，急性发作遵医嘱。',
    ingredients: [
      { name: '冬瓜', role: '利水消肿' },
      { name: '薏米', role: '健脾利湿' },
      { name: '黄瓜', role: '清热利水' },
      { name: '白菜', role: '养胃利水' },
      { name: '豆腐', role: '植物蛋白替代' },
    ],
    dishes: [
      { name: '冬瓜薏米汤', ingredients: '冬瓜、薏米', note: '利水祛湿，少油少盐' },
      { name: '白菜豆腐汤', ingredients: '白菜、豆腐', note: '清淡低嘌呤，日常汤品' },
      { name: '凉拌黄瓜', ingredients: '黄瓜', note: '清热利水，低嘌呤凉菜' },
      { name: '玉米须茶', ingredients: '玉米须', note: '利水消肿，代茶饮用' },
      { name: '薏米山药粥', ingredients: '薏米、山药', note: '健脾利湿，早餐温服' },
    ],
    caution: '急性痛风发作禁盲目食疗，遵医嘱用药；忌啤酒海鲜动物内脏；虾仁肉类急性期避免。',
    voiceTitle: '痛风调理：冬瓜薏米低嘌呤饮食',
    voiceSummary: '痛风平素少嘌呤多饮水。冬瓜薏米汤、白菜豆腐汤、玉米须茶，忌啤酒海鲜，急性发作听医嘱。',
    voiceover: '尿酸高平时要管住嘴。冬瓜薏米汤利水；白菜豆腐汤清淡；泡玉米须茶；薏米山药粥健脾。发作期别乱食补，啤酒海鲜内脏要远离，听医生用药。',
  },

  心悸心慌: {
    name: '心悸心慌',
    icon: '💓',
    category: '睡眠情志',
    alias: ['心慌', '心跳快', '心悸', '怔忡'],
    color: '#ec4899',
    summary: '自觉心跳不宁、怔忡不安，多见气血不足或阴虚火旺。',
    principle: '养血安神、益气宁心，规律作息，忌浓茶咖啡劳累。',
    ingredients: [
      { name: '红枣', role: '养血安神' },
      { name: '桂圆', role: '补益心脾' },
      { name: '莲子', role: '养心安神' },
      { name: '百合', role: '清心安神' },
      { name: '小米', role: '和胃安神' },
    ],
    dishes: [
      { name: '桂圆莲子羹', ingredients: '桂圆、莲子', note: '养心安神，晚间温服' },
      { name: '百合莲子粥', ingredients: '百合、莲子、小米', note: '清心安神，睡前适量' },
      { name: '红枣桂圆茶', ingredients: '红枣、桂圆', note: '养血宁心，日常温饮' },
      { name: '甘麦大枣汤', ingredients: '甘草、小麦、红枣', note: '缓急安神，情志心悸' },
      { name: '红枣山药粥', ingredients: '红枣、山药', note: '健脾养血，气血不足' },
    ],
    caution: '胸痛、晕厥、持续心悸请心内科就诊；甲亢、贫血等需查因；忌浓茶咖啡。',
    voiceTitle: '心悸心慌：莲子百合养心安神',
    voiceSummary: '心悸宜养血安神。桂圆莲子羹、百合莲子粥、红枣桂圆茶，忌浓茶咖啡，胸痛晕厥要就医。',
    voiceover: '心慌心跳快，先养心安神。炖桂圆莲子羹；睡前百合莲子粥；泡红枣桂圆茶；情志不好参考甘麦大枣汤。胸痛晕厥立刻看心脏科，别只靠食疗。',
  },

  孕吐: {
    name: '孕吐',
    icon: '🤰',
    category: '气血虚寒',
    alias: ['妊娠呕吐', '早孕反应', '孕期恶心', '害喜'],
    color: '#f472b6',
    summary: '妊娠早期恶心呕吐，多见冲气上逆、脾胃虚弱。',
    principle: '和胃降逆、清淡易消化，少食多餐，遵医嘱补液。',
    ingredients: [
      { name: '生姜', role: '温中止呕' },
      { name: '小米', role: '和胃安神' },
      { name: '山药', role: '健脾和胃' },
      { name: '橙子', role: '生津开胃' },
      { name: '苹果', role: '生津和胃' },
    ],
    dishes: [
      { name: '生姜红糖水', ingredients: '生姜、红糖', note: '温中止呕，少量温服' },
      { name: '小米粥', ingredients: '小米', note: '养胃易消化，少食多餐' },
      { name: '蒸苹果泥', ingredients: '苹果', note: '生津和胃，恶心时少量' },
      { name: '山药小米粥', ingredients: '山药、小米', note: '健脾止呕，早餐温服' },
      { name: '柠檬蜂蜜水', ingredients: '柠檬、蜂蜜', note: '生津止呕，闻香或少量' },
    ],
    caution: '剧烈呕吐脱水、体重下降请产科就医；忌活血滑利食材；遵医嘱补充维生素。',
    voiceTitle: '孕吐：生姜小米和胃止呕',
    voiceSummary: '孕吐宜和胃少食多餐。生姜红糖水少量、小米粥、蒸苹果泥、山药小米粥，剧烈呕吐要就医。',
    voiceover: '早孕恶心，少食多餐是关键。少量生姜红糖水；熬小米粥；恶心时吃蒸苹果泥；山药小米粥健脾。吐得脱水体重掉要看产科，别硬扛。',
  },

  小儿积食: {
    name: '小儿积食',
    icon: '👧',
    category: '脾胃消化',
    alias: ['积食', '小儿厌食', '腹胀嗳气', '食积不化'],
    color: '#fb923c',
    summary: '小儿食积腹胀、嗳腐口臭、大便酸臭，脾胃运化不足。',
    principle: '消食导滞、健脾和胃，清淡少油，忌强迫追喂。',
    ingredients: [
      { name: '山楂', role: '消食化积' },
      { name: '白萝卜', role: '下气消食' },
      { name: '山药', role: '健脾益气' },
      { name: '苹果', role: '生津消食' },
      { name: '小米', role: '和胃易消化' },
    ],
    dishes: [
      { name: '山楂苹果饮', ingredients: '山楂、苹果', note: '消食化积，饭后少量' },
      { name: '萝卜排骨汤', ingredients: '白萝卜、排骨', note: '消食下气，荤素搭配' },
      { name: '山药小米粥', ingredients: '山药、小米', note: '健脾养胃，早餐温服' },
      { name: '蒸苹果泥', ingredients: '苹果', note: '生津消食，幼儿易接受' },
      { name: '苹果山楂饮', ingredients: '苹果、山楂', note: '开胃消食，温热饮用' },
    ],
    caution: '发热呕吐、精神差立即就医；勿长期禁食；积食重伴便秘遵医嘱。',
    voiceTitle: '小儿积食：山楂苹果消食导滞',
    voiceSummary: '小儿积食宜消食健脾。山楂苹果饮、萝卜排骨汤、山药小米粥，清淡少追喂，发热精神差就医。',
    voiceover: '孩子腹胀口臭大便酸，多是积食。饭后山楂苹果饮；炖萝卜排骨汤消食；山药小米粥健脾；蒸苹果泥好接受。发烧没精神立刻看医生，别硬追着喂。',
  },

  解酒护肝: {
    name: '解酒护肝',
    icon: '🍺',
    category: '代谢湿浊',
    alias: ['宿醉', '酒后不适', '护肝', '醉酒头痛'],
    color: '#64748b',
    summary: '饮酒过量头痛恶心、肝胃不适，食疗辅助解酒护肝。',
    principle: '清热利湿、和胃护肝，多饮水休息，最根本是少饮酒。',
    ingredients: [
      { name: '绿豆', role: '清热解毒' },
      { name: '黄瓜', role: '清热利水' },
      { name: '芹菜', role: '清热平肝' },
      { name: '番茄', role: '生津健胃' },
      { name: '蜂蜜', role: '润燥解毒' },
    ],
    dishes: [
      { name: '葛根绿豆汤', ingredients: '葛根、绿豆', note: '清热解酒，酒后温服' },
      { name: '芹菜番茄汁', ingredients: '芹菜、番茄', note: '清热平肝，鲜榨少量' },
      { name: '蜂蜜柠檬水', ingredients: '蜂蜜、柠檬', note: '生津润燥，宿醉头痛' },
      { name: '绿豆汤', ingredients: '绿豆', note: '清热解毒，酒后适量' },
      { name: '番茄鸡蛋汤', ingredients: '番茄、鸡蛋', note: '养胃生津，酒后清淡' },
    ],
    caution: '呕吐意识障碍立即送医；慢性肝病遵医嘱；解酒不能替代戒酒。',
    voiceTitle: '解酒护肝：葛根绿豆芹菜汤',
    voiceSummary: '酒后宜清热生津护肝。葛根绿豆汤、芹菜番茄汁、蜂蜜柠檬水，多饮水休息，根本是少喝酒。',
    voiceover: '宿醉头痛恶心，先补水清热。葛根绿豆汤；芹菜番茄汁少量；蜂蜜柠檬水；清淡番茄鸡蛋汤。呕吐意识不清要送医，护肝不能代替戒酒。',
  },
};

const SHILIAO_DISEASE_KEYWORD_MAP = {
  祛湿: '湿气重',
  上火: '上火咽痛',
  痘痘: '痤疮粉刺',
  掉发: '脱发',
  月子: '产后体虚',
  催乳: '产后缺乳',
  风热: '风热感冒',
  风寒: '风寒感冒',
  中暑: '暑热中暑',
  减肥: '肥胖减重',
  尿酸: '痛风',
  心慌: '心悸心慌',
  孕吐: '孕吐',
  积食: '小儿积食',
  宿醉: '解酒护肝',
  护肝: '解酒护肝',
};

for (const [key, item] of Object.entries(SHILIAO_DISEASE_DATA)) {
  (item.alias || []).forEach((a) => {
    if (!SHILIAO_DISEASE_KEYWORD_MAP[a]) SHILIAO_DISEASE_KEYWORD_MAP[a] = key;
  });
}

function resolveShiliaoDiseaseKey(query) {
  const q = (query || '').trim();
  if (!q) return null;
  if (SHILIAO_DISEASE_DATA[q]) return q;
  if (SHILIAO_DISEASE_KEYWORD_MAP[q]) return SHILIAO_DISEASE_KEYWORD_MAP[q];
  for (const [kw, key] of Object.entries(SHILIAO_DISEASE_KEYWORD_MAP)) {
    if (q.includes(kw) || kw.includes(q)) return key;
  }
  for (const key of Object.keys(SHILIAO_DISEASE_DATA)) {
    if (key.includes(q) || q.includes(key)) return key;
    const item = SHILIAO_DISEASE_DATA[key];
    if ((item.alias || []).some((a) => a.includes(q) || q.includes(a))) return key;
  }
  return null;
}

function getShiliaoDiseaseList() {
  return Object.values(SHILIAO_DISEASE_DATA);
}
